version: '3.8'
services:

  mongo:
    container_name: 'trading-server-mongo'
    image: mongo:latest
    restart: always
    env_file:
      - .env
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    volumes:
      - mongodb_data:/data/db

  redis:
    image: 'redis:6-alpine'
    container_name: trading-server-redis
    networks:
      - default
    ports:
      - 16380:6379
    volumes:
      - ./data/redis:/data
    logging:
      driver: 'json-file'
      options:
        compress: 'true'
        max-file: '10'
        max-size: '50m'


volumes:
  mongodb_data: