#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"


echo "\n>> Pre-push Hook: Checking branch name..."

BRANCH=`git rev-parse --abbrev-ref HEAD`
PROTECTED_BRANCHES="^(master)"

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
then
  echo "\nCannot push to remote $BRANCH branch, please create your own branch and use PR." && exit 1
fi

echo ">> Finish checking branch name.\n==="

exit 0